# Generated by Django 5.0.6 on 2024-05-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Никнейм"
                    ),
                ),
                ("password", models.CharField(max_length=200, verbose_name="Пароль")),
                ("email", models.CharField(max_length=200, verbose_name="Мэйл")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to=None, verbose_name="Аватар"
                    ),
                ),
                ("reg_date", models.DateTimeField(verbose_name="Дата регистрации")),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=800)),
                ("title", models.CharField(max_length=200, verbose_name="Содержание")),
                ("question_date", models.DateTimeField(verbose_name="Дата создания")),
                ("tags", models.JSONField(blank=True, null=True, verbose_name="Теги")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_hasker.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=800)),
                ("answer_date", models.DateTimeField(verbose_name="Дата создания")),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Флаг правильного ответа"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="my_hasker.user"
                    ),
                ),
            ],
        ),
    ]
