# Generated by Django 5.0.6 on 2024-06-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_hasker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"verbose_name": "Ответ", "verbose_name_plural": "Ответы"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Вопрос", "verbose_name_plural": "Вопросы"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.CreateModel(
            name="AnswerVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.ImageField(
                        choices=[(1, "Vote Up"), (-1, "Vote Down")], upload_to=""
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_hasker.answer",
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_hasker.user",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Голосование: ответ",
                "verbose_name_plural": "Голосование: ответы",
            },
        ),
        migrations.CreateModel(
            name="QuestionVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.ImageField(
                        choices=[(1, "Vote Up"), (-1, "Vote Down")], upload_to=""
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_hasker.question",
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_hasker.user",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Голосование: вопрос",
                "verbose_name_plural": "Голосование: вопросы",
            },
        ),
    ]
